package com.continuum.serviceImpl;

import java.io.StringWriter;

import org.apache.velocity.VelocityContext;
import org.apache.velocity.app.VelocityEngine;




public class EmailTemplateRenderer {
	private static final String TEMPLATE_CONTENT = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                        <h1>Return Requested</h1>\r\n"
			+ "                        <p class=\"colored-text\">Your Return ${RMA_QUALIFIER} ${RMA_NO} has been Requested</p>\r\n"
			+ "                        <p class=\"name\">Hi \"${CUST_NAME}\"</p>\r\n"
			+ "                        <p class=\"main-para\">We're happy to let you know that your Return has been Requested. We will\r\n"
			+ "                            be in\r\n"
			+ "                            touch shortly with an update on your status.</p>\r\n"
			+ "                        <p class=\"sec-para\">Your return reference number is: ${RMA_QUALIFIER} ${RMA_NO} Please keep this\r\n"
			+ "                            number for your\r\n"
			+ "                            records.</p>\r\n"
			+ "                        <p class=\"main-para\">If you would like to see your return status and other returns, please login\r\n"
			+ "                            to\r\n"
			+ "                            <a href=\"http://tld.gocontinuum.ai/\">tld.gocontinuum.ai</a>\r\n"
			+ "                        </p>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	
	public String getTemplateContent() {
		return TEMPLATE_CONTENT;
	}

	private static final String FPASSWORD_TEMPLETE_CONTENT = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/reset-password.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                            <h1>Password Reset</h1>\r\n"
			+ "                            <p class=\"colored-text\">Continuum - Change Your Password</p>\r\n"
			+ "                            <p class=\"main-para\">Hello \"${user_name}\" A request has been received to change the password.</p>\r\n"
			+ "                            <a class=\"btn  button\" href=${RESET_LINK} role=\"button\">Reset Password</a>\r\n"
			+ "                        </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";

	private static final String EMAIL_LINE_ITEM_STATUS_IN_TRANSIT = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                        <h1>Return ${RMA_QUALIFIER} ${RMA_NO} Is Authorized and Awaiting Transit</h1>\r\n"
			+ "                        <p class=\"colored-text\">Return: ${RMA_QUALIFIER} ${RMA_NO} is Ready and Awaiting Transit</p>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	public String getEMAIL_LINE_ITEM_STATUS_IN_TRANSIT() {
		return EMAIL_LINE_ITEM_STATUS_IN_TRANSIT;
	}
	private static final String EMAIL_RMA_STATUS = "";
	
	public String getEMAIL_RMA_STATUS() {
		return EMAIL_RMA_STATUS;
	}

	private static final String EMAIL_NOTE_STATUS = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                        <h1>Return Requested</h1>\r\n"
			+ "                        <p class=\"colored-text\">Your Return ${RMA_QUALIFIER} ${RMA_NO} has been Requested</p>\r\n"
			+ "                        <p class=\"name\">Hi \"${CUST_NAME}\"</p>\r\n"
			+ "                        <p class=\"main-para\">We're happy to let you know that your Return has been Requested. We will\r\n"
			+ "                            be in\r\n"
			+ "                            touch shortly with an update on your status.</p>\r\n"
			+ "                        <p class=\"sec-para\">Your return reference number is: ${RMA_QUALIFIER} ${RMA_NO} Please keep this\r\n"
			+ "                            number for your\r\n"
			+ "                            records.</p>\r\n"
			+ "                        <p class=\"main-para\">If you would like to see your return status and other returns, please login\r\n"
			+ "                            to\r\n"
			+ "                            <a href=\"http://tld.gocontinuum.ai/\">tld.gocontinuum.ai</a>\r\n"
			+ "                        </p>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	
	public String getEMAIL_NOTE_STATUS() {
		return EMAIL_NOTE_STATUS;
	}

	private static final String UNDER_REVIEW_TEMPLATE_CONTENT = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                                <h1>Return Assigned</h1>\r\n"
			+ "                                <p class=\"colored-text\">You have been Assigned RMA: ${RMA_QUALIFIER} ${RMA_NO}</p>\r\n"
			+ "                                <p class=\"sec-para\">${RMA_QUALIFIER} ${RMA_NO} has been assigned you. This Return is now at ${STATUS} for\r\n"
			+ "                                    your action.</p>\r\n"
			+ "                            </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	
	public String getAssignRMATemplate() {
		return UNDER_REVIEW_TEMPLATE_CONTENT;
	}
	
	private String CUSTMER_UNDER_REVIEW_TEMPLATE = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                        <h1>Return ${RMA_QUALIFIER} ${RMA_NO} is Under Review</h1>\r\n"
			+ "                        <p class=\"colored-text\">Your Return ${RMA_QUALIFIER} ${RMA_NO} is Under Review</p>\r\n"
			+ "                        <p class=\"name\">Hi \"${CUST_NAME}\"</p>\r\n"
			+ "                        <p class=\"main-para\">We're happy to let you know that your Return is now Under Review and being\r\n"
			+ "                            handled by ${RP_NAME}. We will be in touch shortly with next steps.</p>\r\n"
			+ "                        <p class=\"sec-para\">Your return reference number is: ${RMA_QUALIFIER} ${RMA_NO} Please keep this number for your\r\n"
			+ "                            records.</p>\r\n"
			+ "                        <p class=\"main-para\">If you would like to see your return status and other returns please login to\r\n"
			+ "                            <a href=\"http://tld.gocontinuum.ai/\">tld.gocontinuum.ai</a></p>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	
	public String getCUSTMER_UNDER_REVIEW_TEMPLATE() {
		return CUSTMER_UNDER_REVIEW_TEMPLATE;
	}
	
	private static final String VENDER_LINE_ITEM_STATUS = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                        <h1>Return Requested</h1>\r\n"
			+ "                        <p class=\"colored-text\">Your Return ${RMA_QUALIFIER} ${RMA_NO} has been Requested</p>\r\n"
			+ "                        <p class=\"name\">Hi \"${CUST_NAME}\"</p>\r\n"
			+ "                        <p class=\"main-para\">We're happy to let you know that your Return has been Requested. We will\r\n"
			+ "                            be in\r\n"
			+ "                            touch shortly with an update on your status.</p>\r\n"
			+ "                        <p class=\"sec-para\">Your return reference number is: ${RMA_QUALIFIER} ${RMA_NO} Please keep this\r\n"
			+ "                            number for your\r\n"
			+ "                            records.</p>\r\n"
			+ "                        <p class=\"main-para\">If you would like to see your return status and other returns, please login\r\n"
			+ "                            to\r\n"
			+ "                            <a href=\"http://tld.gocontinuum.ai/\">tld.gocontinuum.ai</a>\r\n"
			+ "                        </p>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	public String getVENDER_LINE_ITEM_STATUS() {
		return VENDER_LINE_ITEM_STATUS;
	}
	
	private String RETURN_PROCESSOR_NOTE = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                            <h1>Note Added</h1>\r\n"
			+ "                            <p class=\"colored-text\">Continuum - Note Added : ${RMA_QUALIFIER} ${RMA_NO}</p>\r\n"
			+ "                            <p class=\"sec-para\">${ASSIGNED_BY} has assigned item - ${ITEM_NAME} to ${ASSIGNED_TO}. Current Status of Item is ${CURRENT_STATUS}.${FOLLOW_UP_DATE}</p>\r\n"
			+ "                        </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	public String getRETURN_PROCESSOR_NOTE() {
		return RETURN_PROCESSOR_NOTE;
	}
	
	private static final String VENDER_LINE_ITEM_STATUS_CUSTOMER = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                            <h1>Note Added</h1>\r\n"
			+ "                            <p class=\"colored-text\">RMA Note: ${RMA_QUALIFIER} ${RMA_NO}</p>\r\n"
			+ "                            <p class=\"sec-para\">A note has been added on Return ${RMA_QUALIFIER} ${RMA_NO}: ${note}</p>\r\n"
			+ "                        </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	public String getVENDER_LINE_ITEM_STATUS_CUSTOMER() {
		return VENDER_LINE_ITEM_STATUS_CUSTOMER;
	}

	private static final String REQ_MORE_CUST_INFO = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                            <div>\r\n"
			+ "                                <h1>Return ${RMA_NO} Requires More Information</h1>\r\n"
			+ "                            </div>\r\n"
			+ "                            <div>\r\n"
			+ "                                <p class=\"colored-text\">Action Required! Return: ${RMA_QUALIFIER} ${RMA_NO} Requires\r\n"
			+ "                                    more information</p>\r\n"
			+ "                                <p class=\"name\">Hi \"${cust_name}\"</p>\r\n"
			+ "                                <p class=\"main-para\">After reviewing your return, we require some additional information\r\n"
			+ "                                    from you to\r\n"
			+ "                                    continue forward. Please login to the link below to see more</p>\r\n"
			+ "                                <button class=\"button\" ><a href=\"http://${SUB_DOMAIN}gocontinuum.ai\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">View RMA</a></button>\r\n"
			+ "                                <p class=\"sec-para\">Your return reference number is: ${RMA_QUALIFIER} ${RMA_NO} Please\r\n"
			+ "                                    keep this number for your\r\n"
			+ "                                    records</p>\r\n"
			+ "                            </div>\r\n"
			+ "                </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	public String getREQ_MORE_CUST_INFO() {
		return REQ_MORE_CUST_INFO;
	}
	private static final String DENIED_TEMPLATE = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <table role=\"presentation\" class=\"container\">\r\n"
			+ "        <tr>\r\n"
			+ "            <td>\r\n"
			+ "                <div class=\"top-section\">\r\n"
			+ "                    <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                    <div class=\"pt-5\">\r\n"
			+ "                                <h1>Updated RMA Status</h1>\r\n"
			+ "                                <p class=\"colored-text\">Continuum - RMA Status Changed : ${RMA_QUALIFIER} ${RMA_NO}</p>\r\n"
			+ "                                <p class=\"name\">Hi \"${CUST_NAME}\"</p>\r\n"
			+ "                                <p class=\"main-para\">After reviewing your return <b>${RMA_QUALIFIER} ${RMA_NO},</b> we have detrimined that it is not\r\n"
			+ "                                    authorized. A member of the team will be in touch shortly to provide more context. If you\r\n"
			+ "                                    believe wish to dispute this return please reach out to a customer service representative to\r\n"
			+ "                                    discuss this matter.</p>\r\n"
			+ "                            </div>\r\n"
			+ "                </div>\r\n"
			+ "\r\n"
			+ "                <div class=\"bottom-section\">\r\n"
			+ "                    <h1>Got a question?</h1>\r\n"
			+ "                    <h3>We're here to help you</h3>\r\n"
			+ "                    <div class=\"contact-info\">\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_MAIL}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div>\r\n"
			+ "                            <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                            <span>${CLIENT_PHONE}</span>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </div>\r\n"
			+ "            </td>\r\n"
			+ "        </tr>\r\n"
			+ "    </table>\r\n"
			+ "</body>\r\n"
			+ "\r\n"
			+ "</html>\r\n"
			+ "";
	
	public String getDENIED_TEMPLATE() {
		return DENIED_TEMPLATE;
	}
	private static final String RMA_AUTHORIZED_TEMPLATE = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"utf-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
			+ "    <title>Return more info</title>\r\n"
			+ "    <style>\r\n"
			+ "        body {\r\n"
			+ "            font-family: 'Poppins', sans-serif;\r\n"
			+ "            margin: 0;\r\n"
			+ "            padding: 0;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        table {\r\n"
			+ "            width: 60%;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        td {\r\n"
			+ "            padding: 20px;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .container {\r\n"
			+ "            max-width: 100%;\r\n"
			+ "            background-color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section img {\r\n"
			+ "            max-width: 60%;\r\n"
			+ "            margin: 0 auto;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section {\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .top-section h1 {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            line-height: 1.5;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .colored-text {\r\n"
			+ "            color: #078A9B;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .name {\r\n"
			+ "            font-size: 1.2rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            color: #2C2C2C;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .main-para {\r\n"
			+ "            font-size: 1rem;\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-weight: 500;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button {\r\n"
			+ "            border: none;\r\n"
			+ "            background-color: #189D91;\r\n"
			+ "            padding: 0.8rem 2rem;\r\n"
			+ "            color: #FFF;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "            text-decoration: none;\r\n"
			+ "            display: inline-block;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .button:hover {\r\n"
			+ "            background-color: #71bbb5;\r\n"
			+ "            color: #fff;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .sec-para {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            color: #494949;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section {\r\n"
			+ "            margin-top: 1rem;\r\n"
			+ "            background-color: #F8FEFC;\r\n"
			+ "            text-align: center;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h1 {\r\n"
			+ "            color: #0896A9;\r\n"
			+ "            font-size: 1.6rem;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .bottom-section h3 {\r\n"
			+ "            font-size: 1.4rem;\r\n"
			+ "            font-weight: 600;\r\n"
			+ "        }\r\n"
			+ "\r\n"
			+ "        .contact-info img {\r\n"
			+ "            max-width: 30px;\r\n"
			+ "            margin-left: 42%;\r\n"
			+ "            display: flex;\r\n"
			+ "            flex-direction: column;\r\n"
			+ "            align-items: center;\r\n"
			+ "        }\r\n"
			+ "        .contact-info div {\r\n"
			+ "            display: flex;\r\n"
			+ "            align-items: center;\r\n"
			+ "            margin-bottom: 10px; /* Adjust margin as needed */\r\n"
			+ "            margin: auto;\r\n"
			+ "            width: 100%;\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "\r\n"
			+ "        .footer {\r\n"
			+ "            color: #838383;\r\n"
			+ "            font-size: 0.8rem;\r\n"
			+ "            text-align: center;\r\n"
			+ "            padding-top: 4rem;\r\n"
			+ "        }\r\n"
			+ "    </style>\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "    <body>\r\n"
			+ "        <table role=\"presentation\" class=\"container\">\r\n"
			+ "            <tr>\r\n"
			+ "                <td>\r\n"
			+ "                    <div class=\"top-section\">\r\n"
			+ "                        <img class=\"img-responsive\" src=\"https://g2s.blob.core.windows.net/images/mail.png\" alt=\"\">\r\n"
			+ "                            <div class=\"pt-5\">\r\n"
			+ "                                <h1>Updated RMA Status</h1>\r\n"
			+ "                                <p class=\"colored-text\">RMA Status Changed : TLD - 428650</p>\r\n"
			+ "                                <p class=\"sec-para\">Status of TLD - 428650 has been changed to: Authorized</p>\r\n"
			+ "                            </div>\r\n"
			+ "                    </div>\r\n"
			+ "\r\n"
			+ "                    <div class=\"bottom-section\">\r\n"
			+ "                        <h1>Got a question?</h1>\r\n"
			+ "                        <h3>We're here to help you</h3>\r\n"
			+ "                        <div class=\"contact-info\">\r\n"
			+ "                            <div>\r\n"
			+ "                                <img src=\"https://g2s.blob.core.windows.net/images/ic-mail.png\" alt=\"\">\r\n"
			+ "                                <span>${CLIENT_MAIL}</span>\r\n"
			+ "                            </div>\r\n"
			+ "                            <div>\r\n"
			+ "                                <img src=\"https://g2s.blob.core.windows.net/images/ic-phone.png\" alt=\"\">\r\n"
			+ "                                <span>${CLIENT_PHONE}</span>\r\n"
			+ "                            </div>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>\r\n"
			+ "                </td>\r\n"
			+ "            </tr>\r\n"
			+ "        </table>\r\n"
			+ "    </body>\r\n"
			+ "\r\n"
			+ "    </html>\r\n"
			+ "";
	public String getRMA_AUTHORIZED_TEMPLATE() {
		return RMA_AUTHORIZED_TEMPLATE;
	}


	public static String renderFPasswordTemplate(VelocityContext context) {
		VelocityEngine velocityEngine = new VelocityEngine();
		velocityEngine.init();

		try {
			StringWriter writer = new StringWriter();
			velocityEngine.evaluate(context, writer, "EmailTemplate", FPASSWORD_TEMPLETE_CONTENT);
			return writer.toString();
		} catch (Exception ex) {
			ex.printStackTrace();
		}

		return null;
	}


	
	public static String renderer(String template, VelocityContext context) {
		VelocityEngine velocityEngine = new VelocityEngine();
		velocityEngine.init();

		try {
			StringWriter writer = new StringWriter();
			velocityEngine.evaluate(context, writer, "EmailTemplate", template);
			return writer.toString();
		} catch (Exception ex) {
			ex.printStackTrace();
		}

		return null;
	}
	
}