# name: Build and deploy WAR app to Azure Web App - continuum-base-backend

# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Java version
#         uses: actions/setup-java@v1
#         with:
#           java-version: '17'

#       - name: Build with Maven
#         run: mvn clean install

#       - name: Upload artifact to Azure Blob Storage
#         run: |
#           az storage blob upload-batch --account-name continuumbaseblob --account-key sf0G9YVBrKsk87z9rrdBFe9Kx4udwPQWlx5lvQoK60sDTJAHdUXOyYNccZkn5MUqTXL8mYPEKuMz+AStv3UCWA== --destination continuum-base-backend --source '${{ github.workspace }}/continuum-portal/target' --pattern '*.jar' --overwrite
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
      
#       - name: Create destination directory
#         run: mkdir -p '$GITHUB_WORKSPACE/continuum-portal/target'

#       - name: Download artifact from Azure Blob Storage
#         run: |
#           az storage blob download-batch --account-name continuumbaseblob --account-key sf0G9YVBrKsk87z9rrdBFe9Kx4udwPQWlx5lvQoK60sDTJAHdUXOyYNccZkn5MUqTXL8mYPEKuMz+AStv3UCWA== --destination '$GITHUB_WORKSPACE/continuum-portal/target' --source continuum-base-backend
#       - name: List contents of the target directory
#         run: ls -R '$GITHUB_WORKSPACE/continuum-portal/target'

        
#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'continuum-base-backend'
#           slot-name: 'Production'
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_42BE350D49C24BDD80CE369B7ECE97F1 }}
#           package: '$GITHUB_WORKSPACE/continuum-portal/target/continuum-portal-0.0.1-SNAPSHOT.jar'
#         env:
#           JAVA_OPTS: '-jar $WEBSITE_RUN_FROM_PACKAGE'


name: Build and deploy WAR app to Azure Web App - continuum-base-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact to Azure Blob Storage
        run: |
          az storage blob upload-batch --account-name continuumbaseblob --account-key sf0G9YVBrKsk87z9rrdBFe9Kx4udwPQWlx5lvQoK60sDTJAHdUXOyYNccZkn5MUqTXL8mYPEKuMz+AStv3UCWA== --destination continuum-base-backend --source '${{ github.workspace }}/continuum-portal/target' --pattern '*.jar' --overwrite

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    strategy:
      matrix:
        runOnce:
          - deploy: true

    steps:
      - name: Manual Approval
        if: matrix.deploy
        uses: wei/cancel-workflow-action@v2
        with:
          workflow_file: '.github/workflows/backend_deployment.yml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create destination directory
        run: mkdir -p '$GITHUB_WORKSPACE/continuum-portal/target'

      - name: Download artifact from Azure Blob Storage
        run: |
          az storage blob download-batch --account-name continuumbaseblob --account-key sf0G9YVBrKsk87z9rrdBFe9Kx4udwPQWlx5lvQoK60sDTJAHdUXOyYNccZkn5MUqTXL8mYPEKuMz+AStv3UCWA== --destination '$GITHUB_WORKSPACE/continuum-portal/target' --source continuum-base-backend

      - name: List contents of the target directory
        run: ls -R '$GITHUB_WORKSPACE/continuum-portal/target'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'continuum-base-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_42BE350D49C24BDD80CE369B7ECE97F1 }}
          package: '$GITHUB_WORKSPACE/continuum-portal/target/continuum-portal-0.0.1-SNAPSHOT.jar'
        env:
          JAVA_OPTS: '-jar $WEBSITE_RUN_FROM_PACKAGE'
