# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - continuum-backend-uat

on:
  push:
    branches:
      - uat
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact to Azure Blob Storage
        run: |
          az storage blob upload-batch --account-name continuumartifacts --account-key JkrBMwT0pkuGhfBTILLxyr3x3czIfmuhg7JW2MGmLYgimTIW4M5tfNU/4maDJODN3hdEBhL4BZjk+AStsCObNg== --destination uat --source '${{ github.workspace }}/continuum-portal/target' --pattern '*.jar' --overwrite

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      
      - name: Create destination directory
        run: mkdir -p '$GITHUB_WORKSPACE/continuum-portal/target'

      - name: Download artifact from Azure Blob Storage
        run: |
          az storage blob download-batch --account-name continuumartifacts --account-key JkrBMwT0pkuGhfBTILLxyr3x3czIfmuhg7JW2MGmLYgimTIW4M5tfNU/4maDJODN3hdEBhL4BZjk+AStsCObNg== --destination '$GITHUB_WORKSPACE/continuum-portal/target' --source uat

      - name: List contents of the target directory
        run: ls -R '$GITHUB_WORKSPACE/continuum-portal/target'


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'continuum-backend-uat'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_71697269AC884C4BAAD841F7C2C1FAA5 }}
          package: '*.jar'
